import io, glob, os
BS = chr(92); NL = BS + 'n'
d = glob.glob(os.path.expanduser('~/bpi/output/build/libretro-paralleln64-*/'))[0]
p = d + 'mupen64plus-core/src/plugin/audio_libretro/audio_backend_libretro.c'
s = io.open(p + '.orig', encoding='utf-8', newline='').read()

C = []; A = C.append
A('')
A('/* RetroBPI: is the emulator actually keeping up?')
A(' *')
A(' * Gils point: this kind of dirt is usually the CPU failing to keep up. That')
A(' * also explains why every earlier measurement looked perfect -- RetroArch')
A(' * dynamic rate control stretches the audio to hold the ALSA buffer at its')
A(' * target, so a shortfall shows up as continuous resampling-ratio modulation')
A(' * (audible as dirt) rather than as a buffer dip. The margin sat rock steady')
A(' * at 96 ms precisely BECAUSE rate control was working to keep it there.')
A(' *')
A(' * So compare audio-seconds produced against wall-seconds elapsed. A ratio')
A(' * below 1.0 means the core is generating less audio than real time, i.e. the')
A(' * emulator is behind and the frontend is papering over it.')
A(' *')
A(' * NeoGeo is clean on the same speaker, amp and codec, so the analog path is')
A(' * not the problem -- that control rules it out.')
A(' */')
A('#define AUDIO_HEADROOM_GAIN 0.8f')
A('#define AUDIO_TARGET_RATE   48000.0')
A('')
A('static double wall_now(void)')
A('{')
A('    FILE *f = fopen("/proc/uptime", "r");')
A('    double t = 0.0;')
A('    if (f) { if (fscanf(f, "%lf", &t) != 1) t = 0.0; fclose(f); }')
A('    return t;')
A('}')
A('')
A('static void audio_probe(const float *fbuf, const int16_t *sbuf, size_t frames)')
A('{')
A('    static unsigned long nframes = 0, last = 0;')
A('    static double t0 = 0.0, tprev = 0.0;')
A('    static float fpeak = 0.0f;')
A('    static int speak = 0;')
A('    static unsigned long clipped = 0;')
A('    size_t i;')
A('    FILE *f;')
A('    double now, wall_total, wall_delta, audio_total;')
A('    for (i = 0; i < frames * 2; i++) {')
A('        float a = fbuf[i] < 0.0f ? -fbuf[i] : fbuf[i];')
A('        int v = sbuf[i] < 0 ? -sbuf[i] : sbuf[i];')
A('        if (a > fpeak) fpeak = a;')
A('        if (v > speak) speak = v;')
A('        if (v >= 32700) clipped++;')
A('    }')
A('    nframes += frames;')
A('    if (nframes - last >= 48000) {')
A('        now = wall_now();')
A('        if (t0 == 0.0) { t0 = now; tprev = now; }')
A('        wall_total  = now - t0;')
A('        wall_delta  = now - tprev;')
A('        tprev = now;')
A('        audio_total = (double)nframes / 48000.0;')
A('        last = nframes;')
A('        f = fopen("/tmp/glitch.log", "a");')
A('        if (f) {')
A('            /* speed_permille: 1000 = exactly real time. Below 1000 means the')
A('             * emulator is behind and the frontend is stretching audio. */')
A('            fprintf(f, "SEC audio=%.1f wall=%.1f this_sec=%.3f speed_permille=%d peak=%d clip=%lu' + NL + '",')
A('                    audio_total, wall_total, wall_delta,')
A('                    (wall_delta > 0.01) ? (int)(1000.0 / wall_delta) : 0,')
A('                    speak, clipped);')
A('            fclose(f);')
A('        }')
A('        fpeak = 0.0f; speak = 0; clipped = 0;')
A('    }')
A('}')
A('')
helper = '\n'.join(C)

anchor = 'static void aiLenChanged(void* user_data, const void* buffer, size_t size)'
assert s.count(anchor) == 1
s = s.replace(anchor, helper + anchor)
old_q = 'retro_resampler_realloc(&resampler_audio_data, &resampler, "sinc", RESAMPLER_QUALITY_DONTCARE, 1.0);'
s = s.replace(old_q, 'retro_resampler_realloc(&resampler_audio_data, &resampler, "sinc",\n         RESAMPLER_QUALITY_HIGHER, 1.0);')
old_r = '   ratio             = 44100.0 / GameFreq;'
s = s.replace(old_r, '   ratio             = AUDIO_TARGET_RATE / GameFreq;')
old_m = '   max_frames        = (GameFreq > 44100) ? MAX_AUDIO_FRAMES : (size_t)(MAX_AUDIO_FRAMES / ratio - 1);'
s = s.replace(old_m, '   max_frames        = (GameFreq > AUDIO_TARGET_RATE)\n      ? MAX_AUDIO_FRAMES : (size_t)(MAX_AUDIO_FRAMES / ratio - 1);')
old_g = 'convert_s16_to_float(audio_in_buffer_float, raw_data, frames * 2, 1.0f);'
s = s.replace(old_g, 'convert_s16_to_float(audio_in_buffer_float, raw_data, frames * 2,\n         AUDIO_HEADROOM_GAIN);')
old_o = '   out                    = audio_out_buffer_s16;\n'
s = s.replace(old_o, old_o + '\n   audio_probe(audio_out_buffer_float, audio_out_buffer_s16, data.output_frames);\n')
io.open(p, 'w', encoding='utf-8', newline='').write(s)
c = io.open(p, encoding='utf-8', newline='').read()
print('braces balanced :', c.count('{') == c.count('}'))
print('speed probe     :', 'speed_permille' in c)
print('wall clock      :', c.count('wall_now('))
